name: SimpleAuth
main: SimpleAuth\SimpleAuth
version: 1.7.0
api: 1.8.0
load: STARTUP
author: PocketMine Team
authors: [shoghicp]
description: Prevents people to impersonate an account, requering registration and login when connecting.
website: https://github.com/PocketMine/SimpleAuth
commands:
 login:
  description: "Logs into an account"
  usage: "/login <password>"
 register:
  description: "Registers an account"
  usage: "/register <password>"